export const APP_URL = 'http://192.168.42.191:8000';
export const APIv = '/api'


export const Register_Url = `/auth/register`
export const Login_Url = '/auth/login'
export const Logout_Url = '/auth/logout'
export const UpdateAuth_Url = '/auth/update'
export const GetAuthData_Url = '/auth/getdata'
export const ForgetPassword_Url = '/auth/forgetpassword'
export const ResetPassword_Url = '/auth/passwordreset'
export const CreateLecture_URL = '/lecture/create'
export const SearchLecture_Url = '/lecture/search'
export const ReadLecture_Url = '/lecture/read'
export const AttendanceLecture_Url = '/lecture/attendance'
export const AttendanceSubmit_Url = '/attendance/manual'
export const DeleteLecture_Url = '/lecture/delete'
export const QRActivateLecture_Url = '/attendance/Qr'
export const StudentAttendance_Url = '/attendance/student'
export const CollageSearch_Url = '/collage/read'
export const AutoAttendance_Url = '/attendance/auto'
export const ManualPermissionAttendance_Url = '/attendance/permission/manualattendance'
export const UserPermissions_Url = '/attendance/permission/user/list'
export const LecturePermissions_Url = '/attendance/permission/instructor/list'
export const LecturePermissionDelete_Url = '/attendance/permission/delete'
export const LecturePermissionCreate_Url = '/attendance/permission/create'